### PR TITLE
Integrated the latest version of bouncycastle. Changed some method signa...

### PR DESCRIPTION
**Pull request by mdzhigarov**
...tures in OtrEngineHost. Added new method in Session which allows users to check whether SMP negotiation is in progress

### CODE REVIEW

**Comment by gpolitis** [comment]
Hey mdzhigarov, thanks for the patch. Can you please remove the binaries (jar files) and cleanup the pom.xml? And a quick question : do you have any clues as to why this is needed : .decode(content.substring(0, content.length() - 1).getBytes())) ? Thanks!

**Comment by mdzhigarov** [comment]
Hello George,

I want to ask you what to do with the binaries? Because I can not find bouncycastle 1.49 in the Maven Central repo. This is why I put this jar in a local repository.
About .decode(content.substring(0, content.length() - 1).getBytes())) - please see http://lists.jitsi.org/pipermail/dev/2013-April/004097.html .

Regards,
Marin

**Comment by gpolitis** [comment]
Here you go : http://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on/1.49

About .decode(content.substring(0, content.length() - 1).getBytes())), I was actually asking if you have investigated why this this change was necessary. Maybe we're doing something wrong in otr4j. There should be a reason why we need such an ugly hack.

**Comment by ibauersachs** [comment]
The change is because BouncyCastle now checks the sanity of base64 input. See the referenced link for a more detailed explanation.
Do you have a better idea how to get rid of that dot at the end of the messages?

**Comment by gpolitis** [comment]
Hello @ibauersachs thanks for chiming in. In my haste, I hadn't noticed the footnote in your email :) I guess the fix (and not a hack, now that I understand the problem) you provided is the most reasonable way to fix the problem. I just wanted to make sure it's not a real problem in otr4j that needs attention. @mdzhigarov can you include @ibauersachs  detailed explanation as a comment in you patch? Thanks.

**Comment by mdzhigarov** [comment]
Sorry for the inconvenience but I had some hardware problems and in the hurry I accidently deleted my repo. I made a new pull request. Thanks.

**Pull request closed without merging**
